language: cpp

compiler:
  - clang
  - gcc

sudo: required

env:
  - PAM=0
  - PAM=1

arch:
  packages:
    - pam
    - python-docutils
    - qt5-declarative
    - qt5-tools
    - extra-cmake-modules
    - clang
    - git
  script:
    - if [ "$PAM" == "0" ]; then cmake -DBUILD_MAN_PAGES=ON -DENABLE_PAM:BOOL=OFF .; fi
    - if [ "$PAM" == "1" ]; then cmake -DBUILD_MAN_PAGES=ON -DENABLE_PAM:BOOL=ON .; fi
    - make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email: false
  irc:
    - "chat.freenode.net#sddm"
